"""Wrapper for MIDI messages to carry additional metadata."""

import mido


class MidiMessageWrapper:
    """Wrapper for mido.Message with additional metadata."""

    def __init__(self, msg: mido.Message, is_arp: bool = False):
        """Initialize wrapper.

        Args:
            msg: The mido.Message
            is_arp: Whether this message is generated by the arpeggiator
        """
        self.msg = msg
        self.is_arp = is_arp
